

export interface IProductVariation {
  size?: string;   
  color?: string;  
  stock: number;   
  price?: number;   
}

export interface ISpecification {
  name: string;    // e.g., "Sensor Type"
  value: string;   // e.g., "CMOS"
}

export interface IProduct {
  _id?: string;                 // Made optional for creating new products, but present when fetching
  name: string;
  slug: string;
  orderBy?: number;             // New field for custom ordering
  bulletPoints?: string[];      // The short list next to the camera
  description?: string;         // HTML from TextEditor
  specifications: ISpecification[]; // Table data
  images: string[];            // Main gallery images (S3 URLs)
  featureImages: string[];     // Images specifically for the Features tab (S3 URLs)
  basePrice: number; 
  variations: IProductVariation[];
  categories: string[]; // Can be an array of strings when populated or sent from frontend
  deleteImages?: string[];      // Array of S3 URLs to be deleted during an update
  createdAt: string | Date;    // Optional because it's auto-generated by Mongoose
  updatedAt: string;    // Optional because it's auto-generated by Mongoose
}